### ISSUE TITLE
1S111/1 Failed to copy profile sync.

### ISSUE THREAD

**Issue by dudeisbrendan03** [thejhnz/Discord-IPS-Plugin#12]
IPS 4.3 - I've had a discord plugin before (not from you).
Don't really know what to do

**Comment by dudeisbrendan03** [comment]
Just enabled it again and it worked.

**Comment by dudeisbrendan03** [comment]
Doesn't matter - can't link profiles and role syncing doesn't work

**Comment by thejhnz** [comment]
Yeah not a lot I can do without any logs etc. Feel free to fix it and make a pull request 👍

**Comment by dudeisbrendan03** [comment]
New to IPS, and I don't have much experience in PHP - sorry. How would I get the logs from/for IPS?

**Comment by Julien-Rroa** [comment]
I have the same problem = /
```
UPDATE `ibf_forums_forums` forums_forums  SET `parent_id`=16,`redirect_url`=NULL,`skin_id`='0',`can_view_others`=true,`permission_showtopic`=false,`show_rules`='0',`qa_rate_questions`='*',`qa_rate_answers`='*',`forum_allow_rating`=false,`disable_sharelinks`=false,`inc_postcount`=true,`allow_poll`=true,`discord_channel_approved`='0',`discord_channel_unapproved`='0',`discord_post_topics`=false,`discord_post_unapproved_topics`=false,`discord_post_posts`=false,`discord_post_unapproved_posts`=false,`discord_topic_format`='{poster} has just posted a new topic called: "{title}". Read more: {link}',`discord_post_format`='{poster} has just posted a new post to the topic: "{title}". Read more: {link}',`sub_can_post`=true,`redirect_on`=false WHERE id=223 
IPS\Db\Exception: Unknown column 'discord_channel_approved' in 'field list' (1054)
#0 /home/forum/www/system/Db/Db.php(990): IPS\_Db->preparedQuery('UPDATE `ibf_for...', Array)
#1 /home/forum/www/system/Patterns/ActiveRecord.php(492): IPS\_Db->update('forums_forums', Array, Array)
#2 /home/forum/www/system/Node/Model.php(2219): IPS\Patterns\_ActiveRecord->save()
#3 /home/forum/www/system/Node/Model.php(3002): IPS\Node\_Model->save()
#4 /home/forum/www/system/Node/Controller.php(408): IPS\Node\_Model->saveForm(Array)
#5 /home/forum/www/applications/forums/modules/admin/forums/forums.php(122): IPS\Node\_Controller->form()
#6 /home/forum/www/system/Dispatcher/Controller.php(85): IPS\forums\modules\admin\forums\_forums->form()
#7 /home/forum/www/system/Node/Controller.php(62): IPS\Dispatcher\_Controller->execute()
#8 /home/forum/www/applications/forums/modules/admin/forums/forums.php(39): IPS\Node\_Controller->execute()
#9 /home/forum/www/system/Dispatcher/Dispatcher.php(146): IPS\forums\modules\admin\forums\_forums->execute()
#10 /home/forum/www/admin/index.php(14): IPS\_Dispatcher->run()
#11 {main}
```

**Comment by dudeisbrendan03** [comment]
That's not the same issue. 

____
Closing this as we replaced this plugin with our own one
